---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: installer
provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_VERBOSITY:-0}
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: ansible.posix.profile_tasks
      callback_whitelist: profile_tasks, timer, yaml
  inventory:
    hosts:
      all:
        vars:
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

          debian_installer_mirror: ''
          debian_installer_security_mirror: ''
          debian_installer_url: "{{ molecule_iso }}"
          debian_installer_dest: "file://{{ _libvirt_path }}/debian-latest.iso"
          debian_installer_target_dir: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}"

          molecule_libvirt_netaddr: "{{ lookup('env', 'MOLECULE_NET', default='192.168.255.0/24') | ansible.utils.ipv4('network/prefix') }}"
          molecule_libvirt_netsize: "{{ molecule_libvirt_netaddr | ansible.utils.ipaddr('prefix') }}"
          molecule_libvirt_address: "{{ molecule_libvirt_netaddr | ansible.utils.nthhost(1) }}/{{ molecule_libvirt_netsize }}"
          molecule_libvirt_network: "molecule"
          molecule_libvirt_path: "/var/lib/libvirt/debian"
          molecule_distro: "{{ lookup('env', 'MOLECULE_DISTRO', default='current') }}"
          molecule_iso: "{{ lookup('env', 'MOLECULE_ISO') }}"
          molecule_install_dir: "{{ lookup('env', 'MOLECULE_OUTPUT_DIR', default='/tmp/logs') }}"
          molecule_kvm_keypair: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/kvm_key"
          molecule_kvm_guests:
            - installer_hostname: "{{ molecule_distro }}-lvm-10g"
              installer_disk_size: "{{ 10*(1024**3) }}"
              installer_interface:
                static: true
                ipaddress: "{{ molecule_libvirt_netaddr | ansible.utils.nthhost(2) }}"
                network: "{{ molecule_libvirt_netaddr | ansible.utils.ipaddr('network') }}"
                netmask: "{{ molecule_libvirt_netaddr | ansible.utils.ipaddr('netmask') }}"
                gateway: "{{ molecule_libvirt_address | ansible.utils.ipaddr('address') }}"
                nameservers:
                  - 1.1.1.1
                  - 8.8.8.8
              installer_partitioning_method: lvm

            - installer_hostname: "{{ molecule_distro }}-static-10g"
              installer_disk_size: "{{ 10*(1024**3) }}"
              installer_interface:
                static: true
                ipaddress: "{{ molecule_libvirt_netaddr | ansible.utils.nthhost(3) }}"
                network: "{{ molecule_libvirt_netaddr | ansible.utils.ipaddr('network') }}"
                netmask: "{{ molecule_libvirt_netaddr | ansible.utils.ipaddr('netmask') }}"
                gateway: "{{ molecule_libvirt_address | ansible.utils.ipaddr('address') }}"
                nameservers:
                  - 1.1.1.1
                  - 8.8.8.8
              installer_partitioning_method: regular

            - installer_hostname: "{{ molecule_distro }}-lvm-50g"
              installer_disk_size: "{{ 50*(1024**3) }}"
              installer_interface:
                static: true
                ipaddress: "{{ molecule_libvirt_netaddr | ansible.utils.nthhost(4) }}"
                network: "{{ molecule_libvirt_netaddr | ansible.utils.ipaddr('network') }}"
                netmask: "{{ molecule_libvirt_netaddr | ansible.utils.ipaddr('netmask') }}"
                gateway: "{{ molecule_libvirt_address | ansible.utils.ipaddr('address') }}"
                nameservers:
                  - 1.1.1.1
                  - 8.8.8.8
              installer_partitioning_method: lvm

            - installer_hostname: "{{ molecule_distro }}-static-50g"
              installer_disk_size: "{{ 50*(1024**3) }}"
              installer_interface:
                static: true
                ipaddress: "{{ molecule_libvirt_netaddr | ansible.utils.nthhost(5) }}"
                network: "{{ molecule_libvirt_netaddr | ansible.utils.ipaddr('network') }}"
                netmask: "{{ molecule_libvirt_netaddr | ansible.utils.ipaddr('netmask') }}"
                gateway: "{{ molecule_libvirt_address | ansible.utils.ipaddr('address') }}"
                nameservers:
                  - 1.1.1.1
                  - 8.8.8.8
              installer_partitioning_method: regular
              installer_preseed_include: |
                d-i partman-basicfilesystems/no_swap boolean false

verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - prepare
    - converge
    - verify
    - cleanup
